account/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_view
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name='account'

urlpatterns = [
	url(r'^signup/$', views.my_signup.as_view(), name='signup'),
	url(r'^login/$', views.my_login.as_view(), name='login'),
	url(r'^logout/$', auth_view.logout, {'next_page':'blog:index'}, name='logout'),

	url(r'^update/$', views.UpdateProfile.as_view(), name='update'),
	url(r'^update/password/$', views.UpdatePassword.as_view(), name='update_password'),
] 

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.conf.urls import url
from django.conf.urls.static import static
from django.conf import settings

from . import views as blog_view

app_name = 'blog'

urlpatterns = [
	url(r'^$', blog_view.Index.as_view(), name='index'),	
	url(r'^profile/(?P<user>\w+)/$', blog_view.MyProfile.as_view(), name='profile'),
	url(r'^post/(?P<tag>[\w|\W]+)/$', blog_view.SearchingTag.as_view(), name='searchingtag'),
	url(r'^place/(?P<qlocation>[\w|\W]+)/$', blog_view.SearchingLocation.as_view(), name='searchinglocation'),
	url(r'^remove/(?P<pk>\d+)/$',blog_view.RemovePost.as_view(), name='removepost'),
	url(r'^mod/(?P<pk>\d+)/$',blog_view.ModifyPost.as_view(), name='modifypost'),
	url(r'^searching/$',blog_view.Searching.as_view(),name='searching'),
]

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

simple_blog/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('blog.urls', namespace='blog')),
    url(r'^account/', include('account.urls', namespace='account')),
    url(r'^social/',include('social_django.urls', namespace='social')),
]

if settings.DEBUG:
	import debug_toolbar
	urlpatterns += [
		url(r'^__debug__/',include(debug_toolbar.urls)),
	]

blog/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils.text import slugify

class Group(models.Model):
	name = models.CharField(max_length=256, unique=True)

	def __str__(self):
		return self.name

class Profile(models.Model):
	user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
	prof_img = models.ImageField(null=True, blank=True, upload_to='blog')
	name = models.CharField(max_length=128,blank=True)
	group = models.ManyToManyField(Group, blank=True)

	def __str__(self):
		return self.name

	@receiver(post_save,sender=User)
	def update_user_profile(sender,instance,created,**kwargs):
		if created:
			Profile.objects.create(user=instance)
		instance.profile.save()


class Tag(models.Model):
	name = models.CharField(max_length=256,unique=True)

	def __str__(self):
		return self.name


class Post(models.Model):
	author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
	location = models.CharField(max_length=256)	
	q_location = models.SlugField(allow_unicode=True)
	content = models.TextField()
	tags = models.ManyToManyField(Tag,blank=True)
	published = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return self.content[:15]

	def save(self):
		self.q_location = self.location.replace(' ','-')
		super(Post,self).save()
	class Meta:
		ordering = ['-published']

blog/forms.py
from django import forms

from .models import Post, Tag, Profile, Group

class PostForm(forms.ModelForm):

	content = forms.CharField(widget=forms.Textarea(
								attrs = {
									'id':'content',
								}))
	location = forms.CharField(max_length=1024,
							widget=forms.TextInput(
								attrs={
									'id':'location',
								}))
	tags = forms.CharField(required=False,widget=forms.TextInput(
						attrs={
							'id':'tags',
							'placeholder':'Write tags seperate with comma'
						}))
	
	class Meta:
		model = Post
		fields = ['content','location','tags']

blog/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from django.views.generic import ListView, View


from decouple import config

from .models import Post, Tag, Profile, Group
from .forms import PostForm


class Index(ListView):
	def get(self,request):
		if request.user.is_anonymous:
			return redirect('account:signup')
		else:
			form = PostForm()
			posts = Post.objects.prefetch_related('tags').select_related('author').all()
			profile = Profile.objects.select_related('user').filter(user=request.user)
			return render(request,'blog/index.html', {'posts':posts,
													'form':form,
													'profile':profile[0],
													'apikey':config('API_KEY')})
	def post(self,request):
		form = PostForm(request.POST)
		if form.is_valid():
			user = request.user
			content = request.POST.get('content')
			location = request.POST.get('location').replace(',',' ')
			tmp = request.POST.get('tags').split(',')
			post = Post(author=user,content=content,location=location)
			post.save()
			for each in tmp:				
				each = each.strip().replace(' ','_')
				t = Tag.objects.get_or_create(name=each)
				t[0].save()
				post.tags.add(t[0])

		return redirect('blog:index')


class MyProfile(ListView):

	def get(self,request, user):
		if request.user.is_anonymous:
			return redirect('account:login')
		elif request.user.username == user:
			form = PostForm()
			profile = Profile.objects.select_related('user').filter(user__username=user)
			posts = Post.objects.prefetch_related('tags').select_related('author').filter(author__username=user)
			return render(request,'blog/profile.html', {'profile':profile[0],
													'posts':posts,
													'form':form})

		profile = Profile.objects.select_related('user').filter(user__username=user)
		posts = Post.objects.prefetch_related('tags').select_related('author').filter(author__username=user)
		return render(request,'blog/profile.html', {'profile':profile[0],
												'posts':posts,
												'form':False})

	def post(self,request,user):
		form = PostForm(request.POST)
		if form.is_valid():
			user = request.user
			content = request.POST.get('content')
			location = request.POST.get('location').replace(',',' ')
			tmp = request.POST.get('tags').split(',')
			post = Post(author=user,content=content,location=location)
			post.save()
			for each in tmp:				
				each = each.strip().replace(' ','_')
				t = Tag.objects.get_or_create(name=each)
				t[0].save()
				post.tags.add(t[0])

		return redirect('blog:profile',user)

class SearchingTag(ListView):
	def get(self,request,tag):
		form = PostForm()
		posts = Post.objects.prefetch_related('tags').select_related('author').filter(tags__name__icontains=tag)
		profile = Profile.objects.select_related('user').filter(user=request.user)
		return render(request,'blog/index.html', {'posts':posts,
												'form':form,
												'profile':profile[0],
												'apikey':config('API_KEY')})
		
	def post(self,request,tag):
		form = PostForm(request.POST)
		if form.is_valid():
			user = request.user
			content = request.POST.get('content')
			location = request.POST.get('location').replace(',',' ')
			tmp = request.POST.get('tags').split(',')
			post = Post(author=user,content=content,location=location)
			post.save()
			for each in tmp:				
				each = each.strip().replace(' ','_')
				t = Tag.objects.get_or_create(name=each)
				t[0].save()
				post.tags.add(t[0])

		return redirect('blog:index')

class SearchingLocation(ListView):
	def get(self,request,qlocation):
		form = PostForm()
		posts = Post.objects.prefetch_related('tags').select_related('author').filter(q_location__icontains=qlocation)
		profile = Profile.objects.select_related('user').filter(user=request.user)
		return render(request,'blog/index.html', {'posts':posts,
												'form':form,
												'profile':profile[0],
												'apikey':config('API_KEY')})

	def post(self,request,qlocation):
		form = PostForm(request.POST)
		if form.is_valid():
			user = request.user
			content = request.POST.get('content')
			location = request.POST.get('location').replace(',',' ')
			tmp = request.POST.get('tags').split(',')
			post = Post(author=user,content=content,location=location)
			post.save()
			for each in tmp:				
				each = each.strip().replace(' ','_')
				t = Tag.objects.get_or_create(name=each)
				t[0].save()
				post.tags.add(t[0])

		return redirect('blog:index')

class RemovePost(ListView):
	def get(self,request,pk):
		post = Post.objects.filter(pk=pk)
		post.delete()
		referer = request.META.get('HTTP_REFERER')
		return redirect(referer)

class ModifyPost(ListView):
	def get(self,request,pk):		
		post = Post.objects.select_related('author').filter(pk=pk)[0]
		if request.user.id == post.author.id:
			form = PostForm()
			profile = Profile.objects.select_related('user').filter(user=request.user)
			return render(request,'blog/modify.html', {'post':post, 'form':form,
													'profile':profile[0],
													'apikey':config('API_KEY')})
		else:
			return HttpResponse("Error")

	def post(self,request, pk):
		post = Post.objects.select_related('author').filter(pk=pk)[0]
		if post.author.id == request.user.id:
			form = PostForm(request.POST)
			if form.is_valid():				
				content = request.POST.get('content')
				location = request.POST.get('location').replace(',','')
				tmp = request.POST.get('tags').split(',')
				if tmp[-1] == '':
					tmp = tmp[:-1]
				if content != post.content:
					post.content = content
				if location != post.location:
					post.location = location	
				post.save()
				print("tmp:",tmp)

				for t in post.tags.all():
					if t.name in tmp:
						tmp.remove(t.name)
				if tmp:		
					for each in tmp:
						each = each.strip().replace(' ','_')
						t = Tag.objects.get_or_create(name=each)[0]
						t.save()
						post.tags.add(t)
		return redirect('blog:index')

class Searching(ListView):
	def get(self,request):
		q = request.GET.get('query')
		loc_q = Post.objects.prefetch_related('tags').select_related('author').filter(location__icontains=q)
		tag_q = Post.objects.prefetch_related('tags').select_related('author').filter(tags__name__icontains=q)
		posts = (loc_q | tag_q).distinct().order_by('-published')

		form = PostForm()
		profile = Profile.objects.select_related('user').filter(user=request.user)
		return render(request,'blog/index.html', {'posts':posts,
												'form':form,
												'profile':profile[0],
												'apikey':config('API_KEY')})


		
		
		

blog/templates/blog/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
	<meta charset="utf-8">
	<meta name='viewport' content='width=device-width, initial-scale=1' >
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	
	<title>{% block title %}{% endblock %}</title>
	<script src="//developers.kakao.com/sdk/js/kakao.min.js"></script>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
	<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">	

	<link rel="stylesheet" href="{% static 'account/css/account.css' %}">
	<link rel="stylesheet" href="{% static 'blog/css/blog.css' %}">

	<style>
		input#location{
			background-image: url("{% static 'blog/img/map.png' %}");
			background-position: 10px 10px; 
			background-repeat: no-repeat;
			background-size: 10px;
			padding: 10px 20px 12px 40px;
		}
		input#tag{
			background-image: url("{% static 'blog/img/tag.png' %}");
			background-position: 10px 10px; 
			background-repeat: no-repeat;
			background-size: 10px;
			padding: 10px 20px 12px 40px;	
		}
	</style>

</head>
<body>
	<nav class="navbar navbar-default">
		<div class="container">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse"
					data-target="#myNav">
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<a class="navbar-brand" href="{% url 'blog:index' %}">LOCATION</a>
			</div>
			<div class="collapse navbar-collapse" id="myNav">
				<ul class="nav navbar-nav navbar-right">
					<li><a href="{% url 'blog:index' %}">HOME</a></li>						
					{% if user.is_anonymous %}
					<li><a href="{% url 'account:login' %}">LOGIN</a></li>
					<li><a href="{% url 'account:signup' %}">SIGNUP</a></li>
					{% else %}
					<li class="dropdown">
						<a class="dropdown-toggle" data-toggle="dropdown">{{user}}<span class="caret"></span></a>
						<ul class="dropdown-menu">
							<li><a href="{% url 'blog:profile' user %}">PROFILE</a></li>
							<li><a href="{% url 'account:logout' %}">LOGOUT</a></li>
						</ul>
					</li>
					{% endif %}
				</ul>
				<form class="navbar-input navbar-left" size="20" action="{% url 'blog:searching' %}">
					<div class="input-group">
						<input type="text" class="form-control" placeholder="Search" name="query">
						<div class="input-group-btn">
							<button class="btn btn-default" type="submit">
								<i class="glyphicon glyphicon-search"></i>
							</button>
						</div>
					</div>
				</form>
			</div>
		</div>
	</nav>

	

	{% block content %}{% endblock %}
	
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
	<script src="{% static 'account/js/account.js' %}"></script>
	<script src="{% static 'blog/js/blog.js' %}"></script>
	{% block script %}{% endblock %}
</body>
</html>

blog/templates/blog/index.html
{% extends 'blog/base.html' %}
{% load staticfiles %}
{% load humanize %}

{% block title %}HOME{% endblock %}

{% block content %}

	<div class="body">
		<div class="col-xs-1 col-sm-3">
			<div class="hidden-xs" style="text-align: center">
				<div id="setting-btn">
					<a href="{% url 'account:update' %}" style="color:black">
						<span class="fa fa-cog" style="font-size: 15px"></span>
					</a>
				</div>
				<div id="photo">
					{% if not profile.prof_img %}
					<img id="self-image" src="{% static 'account/img/user.png' %}" />
					{% else %}
					<img id="self-image" src="{{ profile.prof_img.url }}" style="opacity:1">
					{% endif %}
				</div>
				<div id="info">
					<a href="{% url 'blog:profile' user %}"  id="profile_name">
						<h3>{{ profile.user.username }}</h3>
					</a>
					{% if profile.name %}
					<h5>({{ profile.name }})</h5>
					{% endif %}
				</div>
				{% if profile.group.all %}
					<div class="group-info">
						{% for group in profile.group.all %}
							<p>{{ group }}</p>
						{% endfor %}
					</div>
				{% endif %}
			</div>
		</div>

		<div class="col-xs-10 col-sm-6" id="post-area">
			<div class="post-form">
				<form method="POST">
				{% csrf_token %}
					<div>
					{% for each in form %}
						{{ each }}
						{% if each.label == 'Location' %}
						<button type="button" class="btn btn-default" id="marker" style="width:6%; display:none" 
							onclick="CurrentLocation()">
							<span class="fa fa-map-marker"></span>
						</button>
						{% endif %}
					{% endfor %}
					</div>
					<div>
						<button type="button" class="btn btn-default" onclick="showLocation()">Location</button>
						<button type="button" class="btn btn-default" onclick="showTag()">Tag</button>
					</div>
					<div class="submit">
						<button type="submit" class="btn btn-default">POST</button>
					</div>
				</form>
			</div>


			<div class="posts">
				{% for post in posts %}
				<div class="post">
					{% if post.author == user %}
					<div id="delete">
						<a href="{% url 'blog:removepost' post.pk %}">
							<span class="fa fa-trash"></span>
						</a>
					</div>
					<div id="mod">
						<a href="{% url 'blog:modifypost' post.pk %}">
							<span class="fa fa-pencil"></span>
						</a>
					</div>
					{% endif %}
					<div class="post-head">
						<p><em><strong>
							{% if post.author == user %}
							<a href="{% url 'blog:profile' post.author %}" style="color:blue">{{ post.author }}</a>
							{% else %}
							<a href="{% url 'blog:profile' post.author %}">{{ post.author }}</a>
							{% endif %}
						</strong></em></p>
						<p><small>
							{{ post.published | naturalday }} -- 
							<a href="{% url 'blog:searchinglocation' post.q_location %}"
							style="border:1px solid #ccc;border-radius: 5px">
								{{ post.location }}
							</a>
						</small></p>
					</div>
					<div class="post-body">
						<p>{{ post.content | linebreaks }}</p>
					</div>
					
					<div class="post-tail">						
					{% if post.tags.all.0.name %}
						{% for tag in post.tags.all %}
							<a href="{% url 'blog:searchingtag' tag.name %}">#{{ tag }}</a>
						{% endfor %}
					{% endif %}
					</div>				
					
				</div>
				{% endfor %}
			</div>

		</div>

		<div class="col-xs-1 col-sm-3">
		</div>

	</div>
{% endblock %}

{% block script %}

<script>
/* Finding current location & serve auto searching box */
function initAutocomplete(){
	var input = document.getElementById('location');
	var searchBox = new google.maps.places.SearchBox(input);	

	searchBox.addListener('places_changed', function() {
		var places = searchBox.getPlaces();
		console.log(places[0].formatted_address);
	});
}

function CurrentLocation(){
	if(navigator.geolocation){
		navigator.geolocation.getCurrentPosition(function(position){
			var pos = {
				lat: position.coords.latitude,
				lng: position.coords.longitude,
			}

			var geourl = "https://maps.googleapis.com/maps/api/geocode/json?latlng="+pos.lat+","+pos.lng+"&key={{apikey}}";

			$.ajax({
				url: geourl,
				type: 'POST',
				success: function(response){
					if(response.status == 'OK'){
						var addr = response.results;
						var size = addr.length;
						document.getElementById("location").value = addr[size-3].formatted_address;
					}
				}
			})
		});
	}
}
CurrentLocation();
</script>
<script src="https://maps.googleapis.com/maps/api/js?key={{apikey}}&libraries=places&callback=initAutocomplete" async defer>
</script>

{% endblock %}

blog/templates/blog/new_post.html
{% extends 'blog/base.html' %}

{% block title %}NEW-POST{% endblock %}

{% block content %}
<div class="body">
	<div class="container" id="post-form">
		<form method="POST">
			{% csrf_token %}
			{% for each in form %}				
				{{ each }}				
			{% endfor %}
			<button class="btn btn-default" type="submit">OK</button>
		</form>
	</div>
</div>
{% endblock %}

blog/templates/blog/profile.html
{% extends 'blog/base.html' %}
{% load staticfiles %}
{% load humanize %}

{% block title %}PROFILE{% endblock %}

{% block content %}
	<div id="wrap">
		<div class="container-fluid" id="profile">
			{% if profile.user == user %}
			<div id="setting-btn">
				<a href="{% url 'account:update' %}" style="color:black">
					<span class="fa fa-cog" style="font-size: 15px"></span>
				</a>
			</div>
			{% endif %}
			<div id="photo">
				{% if not profile.prof_img %}
				<img id="self-image" src="{% static 'account/img/user.png' %}" />
				{% else %}
				<img id="self-image" src="{{ profile.prof_img.url }}" style="opacity:1">
				{% endif %}
			</div>
			<div id="info">
				<h3 style="font-weight: bold">{{ profile.user.username }}</h3>
				{% if profile.name %}
				<h5>({{ profile.name }})</h5>
				{% endif %}
			</div>
			{% if profile.group.all %}
				<div class="group-info">
					{% for group in profile.group.all %}
						<p>{{ group }}</p>
					{% endfor %}
				</div>
			{% endif %}
		</div>
		

		<div calss="container-fluid" id="self-content">
			{% if form %}
			<div class="post-form">
				<form method="POST">
				{% csrf_token %}
					<div>
					{% for each in form %}
						{{ each }}
						{% if each.label == 'Location' %}
						<button type="button" class="btn btn-default" id="marker" style="width:6%; display:none" 
							onclick="CurrentLocation()">
							<span class="fa fa-map-marker"></span>
						</button>
						{% endif %}
					{% endfor %}
					</div>
					<div>
						<button type="button" class="btn btn-default" onclick="showLocation()">Location</button>
						<button type="button" class="btn btn-default" onclick="showTag()">Tag</button>
					</div>
					<div class="submit">
						<button type="submit" class="btn btn-default">POST</button>
					</div>
				</form>
			</div>
			{% endif %}

			<div class="posts">
			{% for post in posts %}
				<div class="post">
					<div id="delete">
						<a href="{% url 'blog:removepost' post.pk %}">
							<span class="fa fa-trash"></span>
						</a>
					</div>
					<div id="mod">
						<a href="{% url 'blog:modifypost' post.pk %}">
							<span class="fa fa-pencil"></span>
						</a>
					</div>
					<div class="post-head">
						<p><em><strong>
							<a href="{% url 'blog:profile' post.author %}" style="color:blue">{{ post.author }}</a>				
						</strong></em></p>
						<p><small>
							{{ post.published | naturalday }} -- 
							<a href="{% url 'blog:searchinglocation' post.q_location %}"
							style="border:1px solid #ccc;border-radius: 5px">
								{{ post.location }}
							</a>
						</small></p>
					</div>
					<div class="post-body">
						<p>{{ post.content | linebreaks }}</p>
					</div>
					
					<div class="post-tail">						
					{% if post.tags.all.0.name %}
						{% for tag in post.tags.all %}
							<a href="{% url 'blog:searchingtag' tag.name %}">#{{ tag }}</a>
						{% endfor %}
					{% endif %}
					</div>				
				</div>
			{% endfor %}
			</div>
		</div>
	</div>
{% endblock %}

blog/templates/blog/searching.html
{% extends 'blog/base.html' %}
{% load staticfiles %}
{% load humanize %}

{% block title %}HOME{% endblock %}

{% block content %}

	<div class="body">
		<div class="col-xs-1 col-sm-3">
			<div class="hidden-xs" style="text-align: center">
				<div id="setting-btn">
					<a href="{% url 'account:update' %}" style="color:black">
						<span class="fa fa-cog" style="font-size: 15px"></span>
					</a>
				</div>
				<div id="photo">
					{% if not profile.prof_img %}
					<img id="self-image" src="{% static 'account/img/user.png' %}" />
					{% else %}
					<img id="self-image" src="{{ profile.prof_img.url }}" style="opacity:1">
					{% endif %}
				</div>
				<div id="info">
					<a href="{% url 'blog:profile' user %}"  id="profile_name">
						<h3>{{ profile.user.username }}</h3>
					</a>
					{% if profile.name %}
					<h5>({{ profile.name }})</h5>
					{% endif %}
				</div>
				{% if profile.group.all %}
					<div class="group-info">
						{% for group in profile.group.all %}
							<p>{{ group }}</p>
						{% endfor %}
					</div>
				{% endif %}
			</div>
		</div>

		<div class="col-xs-10 col-sm-6" id="post-area">
			<div class="post-form">
				<form method="POST">
				{% csrf_token %}
					<div>
					{% for each in form %}
						{{ each }}
						{% if each.label == 'Location' %}
						<button type="button" class="btn btn-default" id="marker" style="width:6%; display:none" 
							onclick="CurrentLocation()">
							<span class="fa fa-map-marker"></span>
						</button>
						{% endif %}
					{% endfor %}
					</div>
					<div>
						<button type="button" class="btn btn-default" onclick="showLocation()">Location</button>
						<button type="button" class="btn btn-default" onclick="showTag()">Tag</button>
					</div>
					<div class="submit">
						<button type="submit" class="btn btn-default">POST</button>
					</div>
				</form>
			</div>


			<div class="posts">
				{% for post in posts %}
				<div class="post">
					{% if post.author == user %}
					<div id="delete">
						<a href="{% url 'blog:removepost' post.pk %}">
							<span class="fa fa-trash"></span>
						</a>
					</div>
					<div id="mod">
						<a href="{% url 'blog:modifypost' post.pk %}">
							<span class="fa fa-pencil"></span>
						</a>
					</div>
					{% endif %}
					<div class="post-head">
						<p><em><strong>
							{% if post.author == user %}
							<a href="{% url 'blog:profile' post.author %}" style="color:blue">{{ post.author }}</a>
							{% else %}
							<a href="{% url 'blog:profile' post.author %}">{{ post.author }}</a>
							{% endif %}
						</strong></em></p>
						<p><small>
							{{ post.published | naturalday }} -- 
							<a href="{% url 'blog:searchinglocation' post.q_location %}"
							style="border:1px solid #ccc;border-radius: 5px">
								{{ post.location }}
							</a>
						</small></p>
					</div>
					<div class="post-body">
						<p>{{ post.content | linebreaks }}</p>
					</div>
					
					<div class="post-tail">						
					{% if post.tags.all.0.name %}
						{% for tag in post.tags.all %}
							<a href="{% url 'blog:searchingtag' tag.name %}">#{{ tag }}</a>
						{% endfor %}
					{% endif %}
					</div>				
					
				</div>
				{% endfor %}
			</div>

		</div>

		<div class="col-xs-1 col-sm-3">
		</div>

	</div>
{% endblock %}

{% block script %}

<script>
/* Finding current location & serve auto searching box */
function initAutocomplete(){
	var input = document.getElementById('location');
	var searchBox = new google.maps.places.SearchBox(input);	

	searchBox.addListener('places_changed', function() {
		var places = searchBox.getPlaces();
		console.log(places[0].formatted_address);
	});
}

function CurrentLocation(){
	if(navigator.geolocation){
		navigator.geolocation.getCurrentPosition(function(position){
			var pos = {
				lat: position.coords.latitude,
				lng: position.coords.longitude,
			}

			var geourl = "https://maps.googleapis.com/maps/api/geocode/json?latlng="+pos.lat+","+pos.lng+"&key={{apikey}}";

			$.ajax({
				url: geourl,
				type: 'POST',
				success: function(response){
					if(response.status == 'OK'){
						var addr = response.results;
						var size = addr.length;
						document.getElementById("location").value = addr[size-3].formatted_address;
					}
				}
			})
		});
	}
}

</script>
<script src="https://maps.googleapis.com/maps/api/js?key={{apikey}}&libraries=places&callback=initAutocomplete" async defer>
</script>

{% endblock %}